//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SentimentType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SentimentType()
        {
            this.Sentiments = new HashSet<Sentiment>();
        }
    
        public int SentimentTypeId { get; set; }
        public string Name { get; set; }
        public int MaxScore { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sentiment> Sentiments { get; set; }
    }
}
