//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sentiment
    {
        public int SentimentId { get; set; }
        public int PostId { get; set; }
        public int SentimentTypeId { get; set; }
        public int Score { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual SentimentType SentimentType { get; set; }
    }
}
